
/*
PROBLEM 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

//   SOLUTION  ->

#include<bits/stdc++.h>
#define ll long long 
#define limit 4000000
using namespace std;
int main()
{
    ll sum=0,a=1,b=0,c;
    for(int i=0;i<10000;i++)
    {
        c =a+b;
        if(sum<=limit)
        {
            if(c%2==0)
                sum+=c;
        }
             
        a=b;
        b=c;
    }
    cout<<sum;
}



// Answer  : 4613732
